/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CarForm.java
 *
 * Created on 14-dec-2009, 14:01:50
 */

package shadowmapper;

import IPL.Item_CARS;
import file_io.Vector3D;
import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author Kilian
 */
public class CarForm extends javax.swing.JFrame {
    private FileManager fm;
    private int ipl;
    private Vector3D position;

    /** Creates new form CarForm */
    public CarForm(FileManager fm, int ipl, Vector3D position) {
        this.fm = fm;
        this.ipl = ipl;
        this.position = position;
        initComponents();
        this.setVisible(true);

        //center the window
        Toolkit toolkit = Toolkit.getDefaultToolkit();
        Dimension screenSize = toolkit.getScreenSize();
        int x = (screenSize.width - this.getWidth()) / 2;
        int y = (screenSize.height - this.getHeight()) / 2;
        this.setLocation(x, y);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboCars = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Car");

        comboCars.setModel(fm.modelVehicles);

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(comboCars, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboCars, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Item_CARS iplItem = new Item_CARS(Finals.gIV);
        iplItem.name = ""+ comboCars.getSelectedItem();
        iplItem.position.x = position.x;
        iplItem.position.y = 0-position.z;
        iplItem.position.z = position.y;
        iplItem.rotation = new Vector3D(0,0,0);
        iplItem.unknown1 = 0;
        iplItem.unknown2 = 0;
        iplItem.unknown3 = 0;
        iplItem.unknown4 = 0;
        iplItem.unknown5 = 0;
        iplItem.unknown6 = 0;
        iplItem.unknown7 = 0;
        fm.ipls[ipl].items_cars.add(iplItem);
        fm.ipls[ipl].changed = true;
        fm.modelIPLItems.addElement(iplItem.name);
        //addHashToIni(name);
        iplItem = null;
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comboCars;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables

}
