

/*
 * About.java
 *
 * Created on 14-jul-2009, 10:47:20
 */

package nl.shadowlink.tools.shadowmapper.gui.about;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Toolkit;

/**
 *
 * @author Shadow-Link
 */
public class About extends javax.swing.JDialog {

    private String[] thanks;
    private int currentHeight = 150;

    private float fps = 1;
    private float finalFPS = 240;
    private long previousTime = 0;

    private float wait = 3;
    private float currentWait = 0;

    /** Creates new form About */
    public About(String[] values, String[] thanks) {
        this.thanks = thanks;
        this.setIconImage(java.awt.Toolkit.getDefaultToolkit().createImage("icon.png"));
        initComponents();

        //center the window
        Toolkit toolkit = Toolkit.getDefaultToolkit();
        Dimension screenSize = toolkit.getScreenSize();
        int x = (screenSize.width - this.getWidth()) / 2;
        int y = (screenSize.height - this.getHeight()) / 2;
        this.setLocation(x, y);

        setText(values);
        this.setVisible(true);
    }

    public void setText(String[] values){
        labelName.setText(values[0]);
        labelVersion.setText(values[1]);
        labelDate.setText(values[2]);
    }

    public void paintPanel(Graphics g){
        for(int i = 0; i < thanks.length; i++){
            g.drawString(thanks[i], (int)(105-thanks[i].length()*2.6), (i*10)+currentHeight);
        }
        if(currentWait >= wait){
            if(currentHeight <= thanks.length*-10){
                currentHeight = 140;
            }else{
                currentHeight -= 1;
            }
            currentWait = 0;
        }else{
            currentWait += 0.7;
        }
        updateFPS();
        this.repaint();
    }

    public void updateFPS(){
        long currentTime= (System.currentTimeMillis());

        ++fps;

        if(currentTime - previousTime >= 1000) {
            previousTime = currentTime;
            finalFPS = fps;
            wait = finalFPS/60;
            fps = 0;
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel() {
            public void paint(Graphics g) {
                paintPanel(g) ;
            }
        };
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelName = new javax.swing.JLabel();
        labelVersion = new javax.swing.JLabel();
        labelDate = new javax.swing.JLabel();
        labelSL = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Shadow Mapper");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 220, 140));

        jLabel1.setText("Special Thanks");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo_about.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 110, 110));

        labelName.setText("program Name");
        getContentPane().add(labelName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        labelVersion.setText("Version 1.0");
        getContentPane().add(labelVersion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        labelDate.setText("01-01-2000");
        getContentPane().add(labelDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        labelSL.setText("©2009 Shadow-Link");
        getContentPane().add(labelSL, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel4.setText("E-Mail: Prince_link_warppipe@hotmail.com");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel3.setText("Website: http://www.Shadow-Link.nl");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelDate;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelSL;
    private javax.swing.JLabel labelVersion;
    // End of variables declaration//GEN-END:variables

}
