package nl.shadowlink.tools.shadowmapper.utils.hashing

class HashTable(
    private val hasher: Hasher
) {

    private val hashes = mutableMapOf<Long, String>()

    fun add(value: String) {
        hashes[hasher.hash(value)] = value
    }

    var missedHashCount = 0

    fun add(hash: Long, value: String) {
        if (!hashes.containsKey(hash)) {
            println("Hash was not generated by IDE entries '$value'")
            missedHashCount++
        }
        hashes[hash] = value
    }

    operator fun get(hash: Long): String? {
        return hashes[hash]
    }
}